# Generated by Django 4.0.4 on 2022-09-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zucolapp', '0002_alter_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(),
        ),
    ]
