# Generated by Django 4.0.4 on 2022-09-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zucolapp', '0003_alter_registration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='number',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='date',
            new_name='Travel_date',
        ),
    ]
